### PR TITLE
Add registration system for CPI classes

### PR DESCRIPTION
**Pull request by nathangong**
I've tested the financial aid system already, however someone will have to test the paid registration system because I'm not sure how to do it without actually paying money. Also, someone will have to verify that the mailing list works with both financial aid and registrations.

### CODE REVIEW

**Comment by nathangong** [comment]
😩
@maggie-j-liu can you authorize the deployment for this PR too? Sorry for asking you so much!

**Comment by nathangong** [comment]
Can you send a pic of the error? I don't think i have access to it

**Comment by maggie-j-liu** [comment]
try to test with `yarn build`
image

**Comment by nathangong** [comment]
@jeffreymeng can you test the registration sometime soon? I think Jay wants this to be published ASAP.

**Comment by jeffreymeng** [comment]
Yes, I'll do it asap. In the meantime, can you make it easier to find the live classes by doing these things:

- The classes button on the navbar should have a dropdown with two options, "Live Classes" and "Video Course".
- The live classes page should take the `/classes` URL (we want to promote live classes over video classes)
- The video classes page should take the `/video-classes` url
- Make sure to update the "looking for self study classes" and "looking for live classes links"

**Comment by nathangong** [comment]
Should we also create an announcement banner on the USACO guide to promote it?

**Comment by jeffreymeng** [comment]
sure

**Comment by nathangong** [comment]
Rip someone has to reauthorize again

**Pull request merged**
