### PR TITLE
Add page for CPG

### PR DESCRIPTION
**Pull request by ADawesomeguy**
This PR adds a very basic page as a start to a CPG page based on the info from #104.

### CODE REVIEW

**Comment by SansPapyrus683** [comment]
damn this looks great!
i take it you don't have a link to the CPG discord rn? it says "join our discord" but there isn't one lol

**Comment by ADawesomeguy** [comment]
I'm honestly not sure whether to link the CPI Discord or if there's a dedicated server for CPG. I can add the link no problem though.

**Comment by cskitty** [comment]
It looks great, thanks! Would it be possible to 

- add a section to enter the email at the top like with [https://joincpi.org/contests](https://joincpi.org/contests) (i think @maggie-j-liu might be looking into the tags for that but (?) )

- in the Community section, add a section saying:
1. Join the CPI discord here: https://discord.gg/Z976aABAA6
2. React in the #start-here channel with the CPG role to gain access to speak in the CPG-exclusive discord community

Thanks!

**Comment by ADawesomeguy** [comment]
Well for the API endpoint for now I can just have it send a request like it does in contest but not specify tags, which I think should be added here: https://github.com/cpinitiative/cpinitiative/blob/b5597afa513b7125bcfafcbcbc339cd58a07d82d/src/pages/api/join-classes-mailing-list.ts#L44-L62

Working on the community section thing now though!

**Review by maggie-j-liu — APPROVED** [review]
looks good! just waiting for a reaction role to be added in the discord, and then we'll merge

**Pull request merged**
