### PR TITLE
Add CerealCodes

### PR DESCRIPTION
**Pull request by jessechoe10**

### CODE REVIEW

**Comment by jessechoe10** [comment]
@maggie-j-liu can you deploy

**Review by maggie-j-liu — COMMENTED** [review]
if you could make the image match the dimensions of the card a bit better, that would be ideal (unless you think this is ok?)
image

**Comment by jessechoe10** [comment]
> if you could make the image match the dimensions of the card a bit better, that would be ideal (unless you think this is ok?) image

What are the card dimensions? Also, you could use the other logo if you want :smile:

**Comment by maggie-j-liu** [comment]
3:5
yeah let me try the other logo

**Review by maggie-j-liu — APPROVED** [review]

**Pull request merged**
