### PR TITLE
Former Team Member Section

### PR DESCRIPTION
**Pull request by cirex-web**
PR for #96 
I got a bit carried away with making the member icons a bit more space-efficient while doing this lol. Let me know if I need to revert/make any changes.

### CODE REVIEW

**Review by maggie-j-liu — CHANGES_REQUESTED** [review]
omg this is so cool

some small details:
rn the space between name and image and name and image below is quite similar; i think it might be easier to parse visually if the name was closer to the image above

image

when the image gets smaller i think the name looks a bit too large?
image

**Comment by cirex-web** [comment]
Glad you like it :D

Instead of making the text smaller, I just made the image bigger. Let me know if that looks okay.

Also,  should I revert back to the old card design for mobile since hovering doesn't work there?

**Comment by maggie-j-liu** [comment]
this looks good! yeah just revert it to the old design for mobile

**Comment by cirex-web** [comment]
Done! 
(I installed a library that checks if the client is on desktop or not in order to decide which card version is shown.)

**Review by maggie-j-liu — APPROVED** [review]
looks good, thank you!

**Pull request merged**
