### PR TITLE
Add self to cpi team.

### PR DESCRIPTION
**Pull request by shaubby**
This is to add myself (Rishabh) to the cpinitiative website.

### CODE REVIEW

**Comment by shaubby** [comment]
I have authorized this.

**Comment by SansPapyrus683** [comment]
i can't merge lmao

**Review by mjh316 — CHANGES_REQUESTED** [review]
Can you remove the formatting or run the format command in npm?

**Comment by shaubby** [comment]
@mjh316 I have fixed the formatting.

**Pull request merged**
